### ISSUE TITLE
开机应用无法完成

### ISSUE THREAD

**Issue by SoulLinkIly** [xzr467706992/Lanthanum_system_toolbox_v2#15]
mi5 miui10 开机应用无法完成，开了自启动，捐赠版，最新测试版，是重启后关闭开机应用，全部调试完，再开开机应用，确实不行，从头至今没有成功过，开机应用测试成功，但是没有用。

**Comment by xzr467706992** [comment]
@SoulLinkIly 测试开机应用显示成功实际没有应用?
