### ISSUE TITLE
最新公测版工具箱充电控制问题

### ISSUE THREAD

**Issue by bubianchuxin012** [xzr467706992/Lanthanum_system_toolbox_v2#21]
机型：libra-Mi 4C
系统：啥都用
问题：手动设置充电最大电流在MIUI10上无效，在类原生上有效。而隔壁微工具箱无论系统如何都有效（MIUI10有效），希望XZR大改进

**Comment by xzr467706992** [comment]
@bubianchuxin012 充电限流没关吧。。
