### ISSUE TITLE
2.0.0B+4处理器一般配置仍不显示cpu

### ISSUE THREAD

**Issue by lakitu12** [xzr467706992/Lanthanum_system_toolbox_v2#4]
机型:红米2 处理器:高通骁龙410

**Comment by xzr467706992** [comment]
@lakitu12 能否打开设置里的输出调试日志 然后进入软件 点处理器基本配置 然后把存储器目录下的Lanthanum_v2文件夹下的output.log内容复制发上来

**Comment by lakitu12** [comment]
Auto generate by Lanthanum system toolbox 2.0.0B4+(18071702)
Don't edit!
--------------------------------
SH:rm -rf /data/data/xzr.La.systemtoolbox/mods
echo @id=1531975346778

--------------------------------
SHR:started
--------------------------------
SUR:started
--------------------------------
SHR:[1531975346778]
--------------------------------
SH:cp /storage/emulated/0/Lanthanum_v2/modules/* /data/data/xzr.La.systemtoolbox/mods
echo @id=1531975348615

--------------------------------
SHR:[1531975348615]
--------------------------------
SHRE:Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
--------------------------------
SU:cat /sys/module/msm_thermal/core_control/enabled
echo @id=1531975355782

--------------------------------
SUR:[1531975355782]0
--------------------------------
SU:if [ -e /sys/class/kgsl/kgsl-3d0 ]
then
echo true
else
echo false
fi
echo @id=1531975355786

--------------------------------

**Comment by lakitu12** [comment]
SUR:[1531975355786]true
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/devfreq/available_frequencies
echo @id=1531975355803

--------------------------------
SUR:[1531975355803]720000000 650000000 550000000 475000000 400000000 310000000 200000000 100000000
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/max_gpuclk
echo @id=1531975355807

--------------------------------
SUR:[1531975355807]720000000
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/devfreq/available_frequencies
echo @id=1531975355819

--------------------------------
SUR:[1531975355819]720000000 650000000 550000000 475000000 400000000 310000000 200000000 100000000
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/devfreq/min_freq
echo @id=1531975355822

--------------------------------
SUR:[1531975355822]720000000
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/devfreq/available_governors
echo @id=1531975355834
--------------------------------
SUR:[1531975355834]bw_hwmon bw_vbif gpubw_mon msm-adreno-tz cpufreq userspace powersave performance simple_ondemand
--------------------------------
SU:cat /sys/class/kgsl/kgsl-3d0/devfreq/governor
echo @id=1531975355838

--------------------------------
SUR:[1531975355838]performance

**Comment by lakitu12** [comment]
--------------------------------
SHRE:Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
--------------------------------

**Comment by xzr467706992** [comment]
@lakitu12 emmmm 还是直接把日志传到某个地方 （比如百度网盘）然后给我链接

**Comment by lakitu12** [comment]
https://pan.baidu.com/s/1C3TmISc30ou102_oq8Smcg

**Comment by xzr467706992** [comment]
问题已找到 部分机型不支持ls -A

**Comment by lakitu12** [comment]
文件夹devices、drivers；文件：drivers_autoprobe、drivers_probe、uevent
